FROM debian:bullseye-slim AS build

ENV DEBIAN_FRONTEND="noninteractive"


RUN apt-get update && apt-get install -y --no-install-recommends \
    # Required for installers
    wget ca-certificates gpg \
    # Utils
    xvfb xauth \
    # Cleanup
    && apt-get autoremove -y && apt-get clean && rm -rf /var/lib/apt/lists/*


COPY ./files/install-box.sh /install-box.sh
RUN chmod +x /install-box.sh && /install-box.sh && rm /install-box.sh


#Install some needed packages
RUN apt-get update \
 && apt-get install -y wget software-properties-common gnupg2 cabextract procps bc htop nano curl

WORKDIR /root

# Clean up APT-Caches
RUN apt-get -y autoremove \
 && apt-get clean autoclean \
 && rm -rf /tmp/* /var/tmp/* /var/lib/apt/lists

# Install wine and winetricks
COPY ./files/install-wine.sh /
RUN bash /install-wine.sh \
 && rm /install-wine.sh


# SET the Echo Folder
VOLUME /ready-at-dawn-echo-arena
WORKDIR /ready-at-dawn-echo-arena/bin/win10
RUN wine wineboot

#VOLUME /root/.wine/drive_c/users/root/AppData/Local/rad/
ARG src="./files/demoprofile.json"
ARG target="/root/.wine/drive_c/users/root/Local Settings/Application Data/rad/echovr/users/dmo/demoprofile.json"
COPY ${src} ${target}

ARG src="./files/settings_mp_v2.json"
ARG target="/root/.wine/drive_c/users/root/AppData/Local/rad/loneecho/settings_mp_v2.json"
COPY ${src} ${target}


#SET Debug-Level, Term and ENTRYPOINT
ENV WINEDEBUG=-all
ENV TERM=xterm
ENTRYPOINT ["bash", "/scripts/dummy.sh"]

